import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}>
        <header className="border-b bg-white">
          <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
            <div className="font-semibold">Klaviyo Multi-Account</div>
            <nav className="flex items-center gap-6 text-sm">
              <a className="px-3 py-2 rounded hover:bg-gray-100 cursor-pointer" href="/dashboard">Profiles</a>
              <div className="relative group">
                <button aria-label="User menu" className="h-9 w-9 rounded-full border bg-white hover:bg-gray-50 hover:border-gray-300 cursor-pointer inline-flex items-center justify-center">
                  <svg className="h-5 w-5 text-gray-700" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                    <circle cx="12" cy="7" r="4" />
                  </svg>
                </button>
                <div className="absolute right-0 top-full mt-2 w-48 rounded-md border bg-white shadow-lg invisible opacity-0 group-hover:visible group-hover:opacity-100 transition">
                  <a href="/setup" className="block px-3 py-2 hover:bg-gray-50 cursor-pointer">Accounts</a>
                  <a href="#" className="block px-3 py-2 hover:bg-gray-50 cursor-pointer">Sign out</a>
                </div>
              </div>
            </nav>
          </div>
        </header>
        <main className="max-w-6xl mx-auto px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
